services:

    kaikmedia_auth_module.add_facebook_js_listener:
        class: Kaikmedia\AuthModule\Listener\AddFacebookJSListener
        arguments:
        - "@zikula_extensions_module.api.variable"
        - "@twig"
        - "@zikula_core.common.theme.assets_js"
        - "@zikula_core.common.theme.asset_helper"
        - "@zikula_core.common.theme.assets_header"
        tags:
            - { name: kernel.event_subscriber }

    kaikmedia_auth_module.add_global_config_js_listener:
        class: Kaikmedia\AuthModule\Listener\AddGlobalConfigListener
        arguments:
        - "@zikula_extensions_module.api.variable"
        - "@twig"
        - "@zikula_core.common.theme.assets_js"
        - "@zikula_core.common.theme.asset_helper"
        - "@zikula_core.common.theme.assets_header"
        tags:
            - { name: kernel.event_subscriber }